version: '3'
services:
  open-interpreter:
    build:
      context: ~/open-interpreter-docker
      dockerfile: Dockerfile  # Use the Dockerfile from the cloned repository
    volumes:
      - ~/open-interpreter-docker:/root  # Mount the current directory to /root in the container
    tty: true  # Allocate a pseudo-TTY for interactive mode
    command: ["interpreter"]  # Run the "interpreter" command when the container starts
